os: linux
dist: xenial
language: cpp

before_install:
  - export CURRENT_PROJ_DIR=$(pwd)
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - export GTEST_DIR=$(pwd)/googletest
  - mkdir build
  - cd build
  - cmake .. -DBUILD_GMOCK=OFF
  - make
  - sudo make install
  - cd ${CURRENT_PROJ_DIR}
  - pip install --user cpp-coveralls

script:
  - make clean
  - make
  - ./PracticeTest

after_success:
  - coveralls --exclude *Test.cpp --exclude ${GTEST_DIR} --gcov-options '\-lpbc'
